### PR TITLE
Minor refactor to simply date formatting

### PR DESCRIPTION
**Pull request by obrien-j**
Fixes: date formatting simplication

## Description of what your PR accomplishes:

Less code. :)

### CODE REVIEW

**Comment by obrien-j** [comment]
Not having linting on the lambda's feels icky.

**Comment by CalvinRodo** [comment]
Agreed the lack of linting is no fun. 

After I have some breathing room I'm going to be using https://github.com/cds-snc/covid-alert-serverless to store the lambda and creating the packages for deployment. 

I was planning on adding all the PR checks on this code in there, (linting, formatting, test automation, etc...)

**Comment by CalvinRodo** [comment]
I'm doing a PR to fix the infra, I'm going to close this and just copy the code over to that one as it fixes this lambda.

**Comment by obrien-j** [comment]
All good. Just poking around last night to get up to speed, figured I'd
leave it a bit better than I found it. :)

**Pull request closed without merging**
