### PR TITLE
fix waf issue set default to allow

### PR DESCRIPTION
**Pull request by tpjods**
Fixes:

I had to set default to allow. This was blocking all traffic.

default {
    allow()
}

### CODE REVIEW

**Comment by CalvinRodo** [comment]
Looks fine to me, ideally we would lock egress down to just AWS API servers but considering the list of IP Ranges are extremely high and have a tendency to change I'm not sure this is reasonable. 

https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html

**Review by CalvinRodo — DISMISSED** [review]
:taco::cat:

**Review by CalvinRodo — DISMISSED** [review]
Sorry shouldn't have approved this first time around. 

The connection of the lambda to the s3 bucket needs to be handled by a VPC endpoint so we can ensure traffic stays within our network. 

https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html

**Comment by tpjods** [comment]
> Sorry shouldn't have approved this first time around.
> 
> The connection of the lambda to the s3 bucket needs to be handled by a VPC endpoint so we can ensure traffic stays within our network.
> 
> https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html

The end point can only be stood up once. Since this is part of the complete stack it uses the one already created in networking TF. If it didn't it would not connect to S3 from inside the vpc.
image

**Review by CalvinRodo — APPROVED** [review]
I unfortunately misunderstood what was happening, due to the existing of an s3 VPC Endpoint and the fact that the Lambda is in a VPC egress is limited to the VPC only. 

This is good to go.

**Pull request merged**
